# tasks/facts.yml

- name: Include os_family vars
  include_vars: "{{ ansible_os_family }}.yml"
  vars:
    targets:
      - Debian
  when: ansible_os_family in targets

- name: (UltraStack) Include UltraStack vars
  include_vars: ultrastack.yml
  when:
    - use_ultrastack is defined
    - use_ultrastack

- name: Check required Apache variables (strings)
  fail:
    msg: |
      Invalid value for variable for '{{ item }}': {{ lookup('vars', item) }}

      Supported types  : String
      Supported values : Any non-null string
  when: >-
    lookup('vars', item) is not string
    or lookup('vars', item) == 0
  with_items: "{{ required_strings }}"

- name: Check required Apache variables (integers)
  fail:
    msg: |
      Invalid value for variable for '{{ item }}': {{ lookup('vars', item) }}

      Supported types  : Integer
      Supported values : A number between 1-65535
  when: >-
    lookup('vars', item)|int < 1
    or lookup('vars', item)|int > 65535
  with_items: "{{ required_ints }}"

- name: Check variable 'systemd_restart_setting'
  fail:
    msg: |
      Invalid value for variable 'systemd_restart_setting': '{{ systemd_restart_setting }}'

      Supported types  : String
      Supported values : "no", "on-success", "on-failure", "on-abnormal",
                         "on-watchdog", "on-abort", "always"
  failed_when: >-
    systemd_restart_setting not in
    ['no', 'on-success', 'on-failure', 'on-abnormal',
    'on-watchdog', 'on-abort', 'always']
    or systemd_restart_setting is not string
    or systemd_restart_setting == 0
  when: >-
    apache_systemd_restart
    or systemd_restart

- name: (Let's Encrypt) Add Apache to certbot_stop_services
  set_fact:
    certbot_stop_services: "{{ certbot_stop_services + [apache_name] }}"
  when:
    - certbot_stop_services is defined
    - apache_name not in certbot_stop_services

- name: (Let's Encrypt) Create certbot_stop_services with Apache
  set_fact:
    certbot_stop_services:
      - "{{ apache_name }}"
  when:
    - certbot_stop_services is not defined
